type Query {
    # The 'filter' and 'sort' arguments provide the OData-like flexibility
    people(filter: PersonFilter, sort: PersonSort): [Person]
    addresses(filter: AddressFilter, sort: AddressSort): [Address]
}

# ── Entities ──────────────────────────────────
type Person {
    id: ID
    email: String
    firstName: String
    lastName: String
    phoneNumber: String
    bio: String
    jobTitle: String
    startDate: String # Usually ISO-8601 strings
}

type Address {
    id: ID
    city: String
    street: String
}

# ── Entity sorts ──────────────────────────────────
enum SortOrder {
    ASC
    DESC
}

input PersonSort {
    field: PersonSortField
    order: SortOrder
}

enum PersonSortField {
    lastName
    firstName
    email
    jobtitle
}

input AddressSort {
    field: AddressSortField
    order: SortOrder
}

enum AddressSortField {
    street
    city
}

# ── Entity filters ──────────────────────────────────
input AddressFilter {
    city: StringFilter
    street: StringFilter
}

input PersonFilter {
    firstName: StringFilter
    lastName: StringFilter
    email: StringFilter
    jobTitle: StringFilter
    startDate: DateFilter
}

# ── Reusable filter inputs ──────────────────────────────────
input StringFilter {
  equals:     String
  notEquals:  String
  contains:   String
  startsWith: String
  isNull:     Boolean
}

input DateFilter {
  equals:      String   # ISO-8601 e.g. "2024-01-01"
  before:      String
  after:       String
  isNull:      Boolean
}
