spring:
  application:
    name: file-analyzer

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/file_analyzer}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    url: ${SPRING_FLYWAY_URL:${spring.datasource.url}}
    user: ${SPRING_FLYWAY_USER:${spring.datasource.username}}
    password: ${SPRING_FLYWAY_PASSWORD:${spring.datasource.password}}

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
